name: dart_hocr
description: A DART model for HOCR XML.
version: 0.1.0

environment:
  sdk: '>=2.18.2 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

dependencies:
  image: ^3.2.2
  xml: ^6.1.0
